#
# Configuration file for the AdminLTE bundle
#
# For more information about the settings visit:
# https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/configurations.md
#
admin_lte:
    options:
        # default image for missing user avatar images
        default_avatar: bundles/adminlte/images/default_avatar.png
        # the color skin
        skin: skin-blue
        # if activated, the boxed_layout will be deactivated
        fixed_layout: false
        # boxed layout (true) or full-screen (false)
        boxed_layout: true
        # initial collapsed state of the sidebar
        collapsed_sidebar: false
        # whether the logo collapses or not
        mini_sidebar: true
        # all tabs in the control sidebar
        control_sidebar:
            home:
                icon: fas fa-home
                template: control-sidebar/home.html.twig
            settings:
                icon: fas fa-cogs
                controller: 'App\Controller\DefaultController::userPreferences'

    knp_menu:
        enable: false
        main_menu: adminlte_main
        breadcrumb_menu: false

    routes:
        adminlte_welcome: homepage
        adminlte_login: fos_user_security_login
        adminlte_login_check: fos_user_security_check
        adminlte_registration: fos_user_registration_register
        adminlte_password_reset: fos_user_resetting_request
        adminlte_message: message
        adminlte_messages: messages
        adminlte_notification: notification
        adminlte_notifications: notifications
        adminlte_task: task
        adminlte_tasks: tasks
        adminlte_profile: fos_user_profile_show
